# Generated by Django 4.0.6 on 2022-08-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_predicateresult_results'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredicateResult',
            new_name='TestResult',
        ),
    ]
